### ISSUE TITLE
Docs how to use it

### ISSUE THREAD

**Issue by iBobik** [opensourceame/bitbucket2gitlab#1]
It is good to write a few sentenses or points how to use this tool.

**Comment by iBobik** [comment]
Project/fork https://github.com/Inbot/bitbucket2gitlab seems better documented.

**Comment by opensourceame** [comment]
Yeah I should write some docs. I wrote the tool in a couple of hours and forgot about it :-)

The other project is better documented but it doesn't import things like milestones which is why I wrote my version. Actually the documentation from that project is about right for this project too. Just download your issues, unzip the file into /tmp, edit the .rb file and run it.

**Comment by iBobik** [comment]
How about to make pull request with your improvements? It is better to not
fork it. :-)

Jan Pobořil

2016-01-25 16:25 GMT+01:00 David Kelly notifications@github.com:

**Comment by opensourceame** [comment]
I didn't fork it. My script was written from scratch.
